/**
 * Responsibility: co-locate the high-coupling runtime chain behind HomeRailHomePanel.
 * Out of scope: click navigation, template-ref adapter wiring, and template structure.
 */
import { computed, type ComputedRef } from 'vue'
import type { ResultMountScrollMetrics } from '../../../../services/home-rail/homeRailResultMountWindow.service'
import {
  hydrateHomeMarketListFromPersistentCache,
  persistHomeMarketListToPersistentCache,
} from '../../../../services/home-rail/homeRailPersistentCacheIntegration.service'
import {
  syncHomeRailHomeMarketListSnapshot,
  syncHomeRailHomeMarketQuerySnapshot,
} from '../../../../services/home-rail/homeRailUpdateCoordinator.service'
import {
  HOME_MARKET_CARD_COPY_HEIGHT_PX,
  HOME_MARKET_CARD_FALLBACK_WIDTH_PX,
  HOME_MARKET_CARD_STAGGER_STEP_MS,
  HOME_MARKET_GRID_COLUMNS,
  HOME_MARKET_GRID_COLUMN_GAP_PX,
  HOME_MARKET_GRID_ROW_GAP_PX,
  HOME_MARKET_MOUNT_BUFFER_BOTTOM_ROWS,
  HOME_MARKET_MOUNT_BUFFER_TOP_ROWS,
  HOME_MARKET_REMOTE_PAGE_SIZE,
  HOME_MARKET_RESULT_ENTER_DURATION_MS,
  HOME_MARKET_RESULT_INITIAL_VISIBLE_COUNT,
  HOME_MARKET_RESULT_LEAVE_DURATION_MS,
  HOME_MARKET_RESULT_LOAD_MORE_COUNT,
  HOME_MARKET_RESULT_SWITCH_DEBOUNCE_MS,
} from './homeRailHomePanel.constants'
import { useHomeRailHomeMarketDataPipeline } from './useHomeRailHomeMarketDataPipeline'
import { useHomeRailHomeMarketEffectsRuntime } from './useHomeRailHomeMarketEffectsRuntime'
import { useHomeRailHomeMarketResultRuntime } from './useHomeRailHomeMarketResultRuntime'
import { useHomeRailHomeSceneLifecycleRuntime } from './useHomeRailHomeSceneLifecycleRuntime'
import { useHomeRailHomeVisualPresentationRuntime } from './useHomeRailHomeVisualPresentationRuntime'
import type { useHomeRailHomeContentState } from './useHomeRailHomeContentState'
import type { useHomeRailHomeRuntimeState } from './useHomeRailHomeRuntimeState'

type HomeRailHomeContentState = ReturnType<typeof useHomeRailHomeContentState>
type HomeRailHomeRuntimeState = ReturnType<typeof useHomeRailHomeRuntimeState>

interface UseHomeRailHomePanelRuntimeOptions {
  contentState: HomeRailHomeContentState
  runtimeState: HomeRailHomeRuntimeState
  isHomePanelActive: ComputedRef<boolean>
  mountScrollMetrics: ComputedRef<ResultMountScrollMetrics | null | undefined>
  emitMarketSearchClick: () => void
  emitMarketTagSelect: (tag: string, index: number) => void
}

export const useHomeRailHomePanelRuntime = (options: UseHomeRailHomePanelRuntimeOptions) => {
  const {
    homeBannerItems,
    bannerDrop,
    marketContent,
    marketTags: sourceMarketTags,
    marketCollection,
    homeAnnouncementItems,
  } = options.contentState
  const {
    hasResolvedInitialHomeContent,
    hasSeenHomePageActivation,
    homeForegroundSignal,
    homePollSignal,
  } = options.runtimeState

  const { homeMarketQueryState, homeMarketRemoteListState } = useHomeRailHomeMarketDataPipeline({
    marketTags: sourceMarketTags,
    scheduleMarketMountWindowSync: () => scheduleMarketMountWindowSync(),
    emitMarketSearchClick: options.emitMarketSearchClick,
    emitMarketTagSelect: options.emitMarketTagSelect,
    remotePageSize: HOME_MARKET_REMOTE_PAGE_SIZE,
    syncMarketListQuerySnapshot: (query) => syncHomeRailHomeMarketQuerySnapshot(query),
    syncResolvedMarketListSnapshot: (query, list, etag) =>
      syncHomeRailHomeMarketListSnapshot(query, list, etag),
    resolveCurrentMarketCollection: () => marketCollection.value,
    resolveCurrentPendingCollectionLength: () => pendingCollection.value.length,
    resolveCurrentMarketResultTotal: () => marketResultTotal.value,
    setMarketCollection: (items) => {
      marketCollection.value = items
    },
    hydratePersistedMarketListSnapshot: (query) => hydrateHomeMarketListFromPersistentCache(query),
    persistResolvedMarketListSnapshot: (query, list) =>
      persistHomeMarketListToPersistentCache(query, list),
  })

  const {
    activeMarketKind,
    marketKindOptions,
    marketTags,
    marketKeyword,
    isMarketSearchVisible,
    activeMarketTagId,
    hasActiveMarketSearch,
    marketListQuery,
    marketListQuerySignature,
    handleMarketSearchClick,
    handleMarketSearchRevealBeforeEnter,
    handleMarketSearchRevealEnter,
    handleMarketSearchRevealAfterEnter,
    handleMarketSearchRevealBeforeLeave,
    handleMarketSearchRevealLeave,
    handleMarketSearchRevealAfterLeave,
    handleMarketKindSelect,
    handleMarketTagSelect,
    handleMarketKeywordInput,
    handleMarketKeywordClear,
    resolveMarketListQuerySnapshot,
    clearHomeMarketSearchState,
    clearMarketListQueryDebounce,
    resetHomeMarketQueryForInactive,
    disposeHomeMarketQueryState,
    syncMarketTagSelection,
  } = homeMarketQueryState

  const {
    isMarketListLoading,
    marketListLoadingPhase,
    hasResolvedRemoteMarketList,
    hasMarketFirstScreenError,
    hasMarketPaginationError,
    marketListResolvedPage,
    clearStagedMarketListUpdate,
    stageMarketListUpdate,
    consumeStagedMarketListUpdate,
    hydrateRemoteMarketListFromPersistentCache,
    reloadRemoteMarketList,
    loadMoreRemoteMarketListPage,
    clearMarketPaginationFeedback,
    markMarketPaginationError,
    markMarketPaginationEndline,
    invalidateMarketPaginationRequest,
  } = homeMarketRemoteListState

  const homeMarketActions = computed(() => marketContent.value.actions)

  const {
    displayedCollection,
    mountedMarketItems,
    marketPlaceholderCardIdSet,
    marketRemovedOverlayItems,
    marketCardEntryPhaseMap,
    marketResultsStageRef,
    marketResultsContentRef,
    marketLoadMoreSentinelRef,
    marketTopSpacerHeight,
    marketBottomSpacerHeight,
    pendingCollection,
    marketResultTotal,
    hasBootstrappedMarketResults,
    marketResultMotionSource,
    marketTransitionPhase,
    queuedMarketRequest,
    marketCurrentEnterAddedIdSet,
    hasMoreMarketItems,
    isMarketExhausted,
    marketResultsStageStyle,
    marketRemovedOverlayLayerStyle,
    syncMountedMarketWindow,
    scheduleMarketMountWindowSync,
    scheduleMarketLoadMoreObserver,
    applyResolvedMarketListResult,
    appendVisibleMarketItems,
    replaceMarketCollectionImmediately,
    startMarketResultSwitch,
    resetHomeMarketResultWindowForInactive,
    disposeHomeMarketResultWindow,
    isBannerSwiperAutoplayEnabled,
    isHomeNoticeSwiperAutoplayEnabled,
    marketSearchAction,
    featuredPlaceholderIcon,
    resolveMarketPlaceholderIcon,
    hasBannerRemoteImage,
    resolveMarketRemovedOverlayItemStyle,
    resolveMarketRemovedOverlayRevealPhase,
    featuredProgressStyle,
    shouldShowHomeMarketFirstScreenLoading,
    shouldShowHomeMarketFirstScreenError,
    shouldShowHomeMarketFirstScreenEmpty,
    shouldRenderHomeBottomFooter,
    homeBottomFooterMode,
    isMarketCardPlaceholder,
    resolveMarketCardEntryClass,
    resolveMarketCardEntryStyle,
  } = useHomeRailHomeMarketResultRuntime({
    resultWindow: {
      isPanelActive: options.isHomePanelActive,
      mountScrollMetrics: options.mountScrollMetrics,
      isMarketListLoading,
      marketCollection,
      marketListResolvedPage,
      paginationQuerySignature: marketListQuerySignature,
      loadMoreMarketListPage: () => loadMoreRemoteMarketListPage(),
      clearMarketPaginationFeedback,
      markMarketPaginationError,
      markMarketPaginationEndline,
      invalidateMarketPaginationRequest,
      syncResolvedMarketListSnapshot: (list) =>
        syncHomeRailHomeMarketListSnapshot(resolveMarketListQuerySnapshot(), list, list.etag),
      syncCurrentHomeVisualImages: () => syncCurrentHomeVisualImages(),
      syncMarketCardRevealStates: (items) => syncMarketCardRevealStates(items),
      applyMarketCardRevealDiff: (diff) => {
        marketCardRevealPhaseMap.value = buildNextMarketRevealPhaseMap(
          diff,
          marketResultMotionSource.value
        )
      },
      clearMarketCardMotionTimeouts: (retainIds) => clearMarketCardMotionTimeouts(retainIds),
      layout: {
        columns: HOME_MARKET_GRID_COLUMNS,
        fallbackCardWidth: HOME_MARKET_CARD_FALLBACK_WIDTH_PX,
        columnGap: HOME_MARKET_GRID_COLUMN_GAP_PX,
        rowGap: HOME_MARKET_GRID_ROW_GAP_PX,
        cardChromeHeight: HOME_MARKET_CARD_COPY_HEIGHT_PX,
        mountBufferTopRows: HOME_MARKET_MOUNT_BUFFER_TOP_ROWS,
        mountBufferBottomRows: HOME_MARKET_MOUNT_BUFFER_BOTTOM_ROWS,
        initialVisibleCount: HOME_MARKET_RESULT_INITIAL_VISIBLE_COUNT,
        loadMoreCount: HOME_MARKET_RESULT_LOAD_MORE_COUNT,
      },
      motion: {
        resultSwitchDebounceMs: HOME_MARKET_RESULT_SWITCH_DEBOUNCE_MS,
        enterDurationMs: HOME_MARKET_RESULT_ENTER_DURATION_MS,
        leaveDurationMs: HOME_MARKET_RESULT_LEAVE_DURATION_MS,
        staggerStepMs: HOME_MARKET_CARD_STAGGER_STEP_MS,
      },
    },
    presentation: {
      isActive: options.isHomePanelActive,
      homeBannerItems,
      homeAnnouncementItems,
      bannerDrop,
      resolveBannerImageUrl: (item) => resolveBannerImageUrl(item),
      marketActions: homeMarketActions,
    },
    resultPresentation: {
      isMarketListLoading,
      marketListLoadingPhase,
      hasResolvedRemoteMarketList,
      hasMarketFirstScreenError,
      hasMarketPaginationError,
      hasMarketImage: (item) => hasMarketImage(item),
      gridColumns: HOME_MARKET_GRID_COLUMNS,
      staggerStepMs: HOME_MARKET_CARD_STAGGER_STEP_MS,
    },
  })

  const {
    marketCardRevealPhaseMap,
    marketImageStateVersion,
    resolveBannerImageUrl,
    resolveFeaturedImageUrl,
    resolveMarketImageUrl,
    hasMarketImage,
    resolveBannerImageRevealKey,
    isBannerImageLoaded,
    isFeaturedImageLoaded,
    resolveFeaturedImagePresentationPhase,
    resolveBannerImageDisplaySource,
    resolveFeaturedImageDisplaySource,
    isHomeVisualImageRevealReady,
    handleHomeVisualImageLoad,
    handleHomeVisualImageError,
    handleHomeVisualImageRetrying,
    clearMarketCardMotionTimeouts,
    syncCurrentHomeVisualImages,
    syncBannerImageRevealStates,
    syncFeaturedImageRevealState,
    syncMarketCardRevealStates,
    buildNextMarketRevealPhaseMap,
    resolveMarketCardPresentationPhase,
    isHomeNoticeLiveReordering,
    isHomeScenePatchMotionReduced,
    logHomeRefreshDebug,
    triggerHomeScenePatchMotionReduction,
    startHomeNoticeLiveReorder,
    startHomePullRefreshPresentation,
    waitForRefreshPresentation,
    resetHomeVisualRevealForInactive,
    resetHomeLocalRuntimeForInactive,
    disposeHomeVisualReveal,
    disposeHomeLocalRuntime,
  } = useHomeRailHomeVisualPresentationRuntime({
    contentState: options.contentState,
    runtimeState: options.runtimeState,
    isHomePanelActive: options.isHomePanelActive,
    mountedMarketItems,
    marketPlaceholderCardIdSet,
    isMarketListLoading,
    marketTransitionPhase,
    queuedMarketRequest,
    clearStagedMarketListUpdate: () => clearStagedMarketListUpdate(),
    reloadMarketResultPresentationForRefresh: (reason) =>
      reloadMarketList({
        immediate: true,
        preserveVisibleCount: reason === 'pull-refresh',
        forceReplay: reason === 'pull-refresh',
        motionSource: reason === 'pull-refresh' ? 'manual-refresh' : 'manual-query-switch',
      }),
  })

  const {
    refreshContent,
    reloadMarketList,
    handleHomeMarketFirstScreenRetry,
    handleHomeMarketLoadMoreRetry,
    runHomeActivationCheck,
    runHomeVisibleUpdateCheck,
    initializeHomeContent,
  } = useHomeRailHomeSceneLifecycleRuntime({
    contentState: options.contentState,
    runtimeState: options.runtimeState,
    isHomePanelActive: options.isHomePanelActive,
    marketListQuerySignature,
    activeMarketTagId,
    hasBootstrappedMarketResults,
    marketCollection,
    marketResultTotal,
    clearHomeMarketSearchState,
    clearMarketListQueryDebounce,
    clearStagedMarketListUpdate,
    hydrateRemoteMarketListFromPersistentCache,
    reloadRemoteMarketList,
    resolveMarketListQuerySnapshot,
    syncMarketTagSelection,
    consumeStagedMarketListUpdate,
    stageMarketListUpdate,
    applyResolvedMarketListResult,
    replaceMarketCollectionImmediately,
    scheduleMarketLoadMoreObserver,
    appendVisibleMarketItems,
    syncCurrentHomeVisualImages,
    syncBannerImageRevealStates,
    syncFeaturedImageRevealState,
    logHomeRefreshDebug,
    triggerHomeScenePatchMotionReduction,
    startHomeNoticeLiveReorder,
    startHomePullRefreshPresentation,
  })

  useHomeRailHomeMarketEffectsRuntime({
    marketTags,
    marketListQuery,
    marketListQuerySignature,
    homeBannerItems,
    bannerDrop,
    mountedMarketItems,
    displayedCollection,
    pendingCollection,
    hasMoreMarketItems,
    hasResolvedInitialHomeContent,
    hasSeenHomePageActivation,
    isActive: options.isHomePanelActive,
    homeForegroundSignal,
    homePollSignal,
    marketImageStateVersion,
    mountScrollMetrics: options.mountScrollMetrics,
    syncMarketTagSelection,
    syncMarketListQuerySnapshot: () => {
      syncHomeRailHomeMarketQuerySnapshot(resolveMarketListQuerySnapshot())
    },
    clearStagedMarketListUpdate,
    reloadMarketList,
    resolveBannerImageUrl,
    resolveFeaturedImageUrl,
    resolveMarketImageUrl,
    isHomeVisualImageRevealReady,
    resolveBannerImageDisplaySource,
    resolveFeaturedImageDisplaySource,
    syncCurrentHomeVisualImages,
    syncBannerImageRevealStates,
    syncFeaturedImageRevealState,
    syncMountedMarketWindow,
    syncMarketCardRevealStates,
    scheduleMarketMountWindowSync,
    scheduleMarketLoadMoreObserver,
    resetHomeMarketResultWindowForInactive,
    resetHomeVisualRevealForInactive,
    resetHomeMarketQueryForInactive,
    resetHomeLocalRuntimeForInactive,
    startMarketResultSwitch,
    runHomeActivationCheck,
    runHomeVisibleUpdateCheck,
    disposeHomeMarketQueryState,
    disposeHomeVisualReveal,
    disposeHomeMarketResultWindow,
    disposeHomeLocalRuntime,
    initializeHomeContent,
  })

  return {
    activeMarketKind,
    marketKindOptions,
    marketTags,
    marketKeyword,
    isMarketSearchVisible,
    activeMarketTagId,
    hasActiveMarketSearch,
    handleMarketSearchClick,
    handleMarketSearchRevealBeforeEnter,
    handleMarketSearchRevealEnter,
    handleMarketSearchRevealAfterEnter,
    handleMarketSearchRevealBeforeLeave,
    handleMarketSearchRevealLeave,
    handleMarketSearchRevealAfterLeave,
    handleMarketKindSelect,
    handleMarketTagSelect,
    handleMarketKeywordInput,
    handleMarketKeywordClear,
    isHomeNoticeLiveReordering,
    isHomeScenePatchMotionReduced,
    isBannerSwiperAutoplayEnabled,
    isHomeNoticeSwiperAutoplayEnabled,
    marketSearchAction,
    featuredPlaceholderIcon,
    resolveMarketPlaceholderIcon,
    hasBannerRemoteImage,
    resolveMarketRemovedOverlayItemStyle,
    resolveMarketRemovedOverlayRevealPhase,
    featuredProgressStyle,
    shouldShowHomeMarketFirstScreenLoading,
    shouldShowHomeMarketFirstScreenError,
    shouldShowHomeMarketFirstScreenEmpty,
    shouldRenderHomeBottomFooter,
    homeBottomFooterMode,
    isMarketCardPlaceholder,
    resolveMarketCardEntryClass,
    resolveMarketCardEntryStyle,
    mountedMarketItems,
    marketPlaceholderCardIdSet,
    marketRemovedOverlayItems,
    marketCardEntryPhaseMap,
    marketResultsStageRef,
    marketResultsContentRef,
    marketLoadMoreSentinelRef,
    marketTopSpacerHeight,
    marketBottomSpacerHeight,
    marketResultTotal,
    hasMoreMarketItems,
    isMarketExhausted,
    marketResultsStageStyle,
    marketRemovedOverlayLayerStyle,
    displayedCollection,
    marketResultMotionSource,
    marketCurrentEnterAddedIdSet,
    resolveBannerImageUrl,
    resolveFeaturedImageUrl,
    resolveMarketImageUrl,
    hasMarketImage,
    resolveBannerImageRevealKey,
    isBannerImageLoaded,
    isFeaturedImageLoaded,
    resolveFeaturedImagePresentationPhase,
    isHomeVisualImageRevealReady,
    handleHomeVisualImageLoad,
    handleHomeVisualImageError,
    handleHomeVisualImageRetrying,
    resolveMarketCardPresentationPhase,
    handleHomeMarketFirstScreenRetry,
    handleHomeMarketLoadMoreRetry,
    refreshContent,
    waitForRefreshPresentation,
  }
}
